subdir-ccflags-y := -Iadapter/klibc/include/phoenix -Iadapter/klibc/include/sh_kapi -Iadapter/klibc/include/sh_kapi/arch/$(ARCH)

obj-y	:= sh_sym_kapi.o
obj-y	+= sh_task_kapi.o
obj-y	+= sh_regs_kapi.o

obj-y	+= arch/$(ARCH)/
