obj-y     = boot_allotter.o early_map.o mem_init.o \
	    page_allotter.o beehive_allotter.o mmu.o mem_cmd.o init_mm.o \
	    phys_regions.o page_num.o memory.o swap.o \
	    readahead.o truncate.o page_cache.o page_writeback.o page_flush.o
