dtb-$(CONFIG_ARCH_ZX296718) += zx296718.dtb
dtb-$(CONFIG_ZX296718_PCBOX) += zx296718_pcbox.dtb
dtb-$(CONFIG_ARCH_ZX296716) += zx_a16c00.dtb
dtb-$(CONFIG_ARCH_ZX296716) += zx_a16t01.dtb
dtb-$(CONFIG_ARCH_ZX296716) += zx_a16c02.dtb
dtb-$(CONFIG_ARCH_ZX296716) += zx_a16t03.dtb
dtb-$(CONFIG_ARCH_ZX296716) += zx_a16t05.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
