obj-y := vfs.o mount.o super.o file.o open.o node_cache.o node.o \
	node_bond.o block_dev.o char_dev.o cache_space.o block_io.o \
	block_buf.o writeback.o fs_type.o stat.o context.o readdir.o \
	aio.o bad_node.o direct_io.o attr.o simple.o

obj-y += ramfs/
obj-y += devfs/
obj-y += lext3/
obj-y += journal/
